version: '3.8'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3309:3306
    networks:
      - proposta
    environment:
      - MYSQL_DATABASE=proposta
      - MYSQL_ROOT_PASSWORD=Zup@2206
    volumes:
      - mysql:/var/lib/mysql

  app:
    image: guilhermejcs/proposta
    restart: on-failure
    links:
      - db
    ports:
      - 8080:8080
    networks:
      - proposta
    depends_on:
      - db
    environment:
      - BANCO_URL=jdbc:mysql://db:3306/proposta
      - CARTAO_CLIENT=http://contas:8888
      - CONSULTA_CLIENT=http://analise:9999
volumes:
  mysql:

networks:
  proposta:
    name: rede_proposta
    driver: bridge